### PR TITLE
Upgrade project to Swift 3

### PR DESCRIPTION
**Pull request by dagio**
Note : It will only work with iOS 9 for the moment. There is an issue with accessibility or KIF on iOS 10 that I did not sorted out

### CODE REVIEW

**Comment by Serchinastico** [comment]
Hello @dagio ,

Sorry for the delay, I just reviewed your code and it looks good to me. 

I've seen some minor naming issues and fixed KIF tests on top of your code so, do you mind applying those changes to your PR so that we can merge it?

Proposed changes can be found here: https://gist.github.com/Serchinastico/0b149a7f766201f5458c4d20e23cb2b0 

Thank you for your PR and time.

**Comment by dagio** [comment]
@Serchinastico I applied your patch 👍

**Comment by Serchinastico** [comment]
Yeah, it's still failing due to an old travis configuration file 😅 . Let me see if I can fix it so that we can merge your branch.

**Comment by Serchinastico** [comment]
Cool! Got it working by just changing the travis configuration, I'm merging this PR.

Thank you very much for your time and work!

**Pull request merged**
